const examsMap: { [key: string]: string } = {
  enem: 'ENEM',
  fuvest: 'FUVEST',
  // oab: { label: 'OAB' },
};

const courseMap: { [key: string]: string } = {
  medicina: 'Medicina',
  odontologia: 'Odontologia',
  enfermagem: 'Enfermagem',
  farmacia: 'Farmácia',
  fisioterapia: 'Fisioterapia',
  psicologia: 'Psicologia',
  direito: 'Direito',
  administracao: 'Administração',
  ciencias_contabeis: 'Ciências Contábeis',
  publicidade_propaganda: 'Publicidade e Propaganda',
  design_grafico: 'Design Gráfico',
  arquitetura_urbanismo: 'Arquitetura e Urbanismo',
  educacao_fisica: 'Educação Física',
  pedagogia: 'Pedagogia',
  historia: 'História',
  geografia: 'Geografia',
  biologia: 'Biologia',
  matematica: 'Matemática',
  fisica: 'Física',
  quimica: 'Química',
  engenharia_civil: 'Engenharia Civil',
  engenharia_eletrica: 'Engenharia Elétrica',
  engenharia_mecanica: 'Engenharia Mecânica',
  engenharia_producao: 'Engenharia de Produção',
  engenharia_quimica: 'Engenharia Química',
  engenharia_computacao: 'Engenharia de Computação',
  engenharia_software: 'Engenharia de Software',
  ciencia_computacao: 'Ciência da Computação',
  sistemas_informacao: 'Sistemas de Informação',
  ads: 'Análise e Desenvolvimento de Sistemas',
  jogos_digitais: 'Tecnologia em Jogos Digitais',
  relacoes_internacionais: 'Relações Internacionais',
  servico_social: 'Serviço Social',
  jornalismo: 'Jornalismo',
  letras_portugues: 'Letras - Português',
  letras_ingles: 'Letras - Inglês',

  artes_cenicas: 'Artes Cênicas',
  artes_visuais: 'Artes Visuais',
  astronomia: 'Astronomia',
  audiovisual: 'Audiovisual',
  biblioteconomia: 'Biblioteconomia',
  biotecnologia: 'Biotecnologia',
  ciencias_agrarias: 'Ciências Agrárias',
  ciencias_atuariais: 'Ciências Atuariais',
  ciencias_biomedicas: 'Ciências Biomédicas',
  ciencia_dados: 'Ciência de Dados',
  ciencias_natureza: 'Ciências da Natureza',
  ciencias_alimentos: 'Ciências dos Alimentos',
  ciencias_fisicas_biomoleculares: 'Ciências Físicas e Biomoleculares',
  ciencias_sociais: 'Ciências Sociais',
  economia: 'Economia',
  editacao: 'Editoração',
  educomunicacao: 'Educomunicação',
  engenharia_aeronautica: 'Engenharia Aeronáutica',
  engenharia_agronomica: 'Engenharia Agronômica',
  engenharia_ambiental: 'Engenharia Ambiental',
  engenharia_bioquimica: 'Engenharia Bioquímica',
  engenharia_biossistemas: 'Engenharia de Biossistemas',
  engenharia_materiais: 'Engenharia de Materiais',
  engenharia_materiais_manufatura: 'Engenharia de Materiais e Manufatura',
  engenharia_minas: 'Engenharia de Minas',
  engenharia_petroleo: 'Engenharia de Petróleo',
  engenharia_fisica: 'Engenharia Física',
  engenharia_florestal: 'Engenharia Florestal',
  engenharia_mecatronica: 'Engenharia Mecatrônica',
  engenharia_metalurgica: 'Engenharia Metalúrgica',
  engenharia_naval: 'Engenharia Naval',
  estatistica: 'Estatística',
  filosofia: 'Filosofia',
  financas_negocios: 'Finanças e Negócios',
  fisica_computacional: 'Física Computacional',
  fisica_medica: 'Física Médica',
  fonoaudiologia: 'Fonoaudiologia',
  geociencias_ambiental: 'Geociências e Educação Ambiental',
  geofisica: 'Geofísica',
  gerontologia: 'Gerontologia',
  gestao_ambiental: 'Gestão Ambiental',
  gestao_politicas_publicas: 'Gestão de Políticas Públicas',
  informatica_biomedica: 'Informática Biomédica',
  lazer_turismo: 'Lazer e Turismo',
  letras: 'Letras',
  marketing: 'Marketing',
  matematica_aplicada: 'Matemática Aplicada',
  matematica_aplicada_negocios: 'Matemática Aplicada a Negócios',
  matematica_aplicada_computacao_cientifica: 'Matemática Aplicada e Computação Científica',
  matematica_aplicada_computacional: 'Matemática Aplicada e Computacional',
  medicina_veterinaria: 'Medicina Veterinária',
  meteorologia: 'Meteorologia',
  musica: 'Música',
  nutricao: 'Nutrição',
  nutricao_metabolismo: 'Nutrição e Metabolismo',
  obstetricia: 'Obstetrícia',
  oceanografia: 'Oceanografia',
  publicidade: 'Publicidade e Propaganda',
  saude_publica: 'Saúde Pública',
  terapia_ocupacional: 'Terapia Ocupacional',
  textil_moda: 'Têxtil e Moda',
  turismo: 'Turismo',
  zootecnia: 'Zootecnia',
};

export default { courseMap, examsMap };
